steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - .
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
    id: TagLatest
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
    id: PushLatest